services:
  api:
    image: ghcr.io/odrymark/aimusicapp/api:latest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      - Jwt__Key=${JWT__KEY}
      - Jwt__Issuer=${JWT__ISSUER}
      - Jwt__Audience=${JWT__AUDIENCE}
      - Jwt__ExpireMinutes=${JWT__EXPIREMINUTES}
      - RefreshToken__ExpireDays=${REFRESHTOKEN__EXPIREDAYS}
      - R2__AccessKey=${R2__ACCESSKEY}
      - R2__SecretKey=${R2__SECRETKEY}
      - R2__BucketName=${R2__BUCKETNAME}
      - R2__Endpoint=${R2__ENDPOINT}
      - FeatureHub__Url=${FEATUREHUB__URL}
      - FeatureHub__SdkKey=${FEATUREHUB__SDKKEY}
      - Genius__APIKey=${GENIUS__APIKEY}
    restart: always
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  ollama-init:
    image: ollama/ollama
    depends_on:
      - ollama
    volumes:
      - ollama_data:/root/.ollama
      - ./server/AI_backend/Modelfile:/Modelfile
    networks:
      - app-network
    entrypoint: ["/bin/sh", "-c", "sleep 5 && ollama pull qwen3:8b && ollama create song-model -f /Modelfile"]
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: "no"

  ai_backend:
    image: ghcr.io/odrymark/aimusicapp/ai_backend:latest
    depends_on:
      - ollama-init
    restart: always
    networks:
      - app-network

  client:
    image: ghcr.io/odrymark/aimusicapp/client:latest
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
    networks:
      - app-network

  featurehub:
    image: featurehub/party-server:latest
    restart: always
    volumes:
      - ./server/featurehub:/db
    ports:
      - "8085:8085"
    networks:
      - app-network
    environment:
      - PORT=8085
networks:
  app-network:
    driver: bridge
volumes:
  ollama_data:
